### ISSUE TITLE
Fix word wrap on long discussion responses

### ISSUE THREAD

**Issue by jonmchu** [calblueprint/lavamae#39]
<img width="837" alt="screen shot 2016-10-16 at 3 44 04 pm" src="https://cloud.githubusercontent.com/assets/8663702/19421493/7d65e090-93b7-11e6-9e05-22f46958e332.png">

**Comment by TheXienator** [comment]
Also present in discussions content
<img width="1280" alt="screen shot 2016-10-16 at 3 46 46 pm" src="https://cloud.githubusercontent.com/assets/8731630/19421509/cc35b07e-93b7-11e6-89ac-b06346d69e34.png">
